services:
  postgres:
    image: postgres:16-alpine
    ports:
      - '5433:5432'
    env_file:
      - ../.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB']
      interval: 2s
      timeout: 3s
      retries: 10
      start_period: 10s
    command: >
      postgres
      -c fsync=off
      -c synchronous_commit=off
      -c full_page_writes=off
      -c checkpoint_segments=32
      -c checkpoint_completion_target=0.9
      -c wal_buffers=16MB
      -c shared_buffers=256MB
      -c effective_cache_size=512MB
    tmpfs:
      - /tmp
      - /var/run/postgresql

volumes:
  postgres_data:
